version: '3.8'

services:
  web:
    container_name: "web"
    build:
      dockerfile: Dockerfile
    command: daphne -b 0.0.0.0 -p 8000 vin_bigdata.asgi:application
    volumes:
      - ./:/app/
    ports:
      - 8000:8000
    env_file:
      - ./dev.local.env
    depends_on:
      - db
    networks:
      - vin_bigdata
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./db.local.env
    networks:
      - vin_bigdata

volumes:
  postgres_data:

networks:
  vin_bigdata:
    driver: bridge